/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as FavoriteRouteImport } from './routes/favorite'
import { Route as HelloRouteImport } from './routes/hello'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardSkillsRouteImport } from './routes/dashboard/skills'
import { Route as SkillsSkillIdRouteImport } from './routes/skills/$skillId'
import { Route as SkillsNewRouteImport } from './routes/skills/new'
import { Route as UsersUsernameSkillsSkillIdRouteImport } from './routes/users/$username/skills/$skillId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoriteRoute = FavoriteRouteImport.update({
  id: '/favorite',
  path: '/favorite',
  getParentRoute: () => rootRouteImport,
} as any)
const HelloRoute = HelloRouteImport.update({
  id: '/hello',
  path: '/hello',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSkillsRoute = DashboardSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const SkillsSkillIdRoute = SkillsSkillIdRouteImport.update({
  id: '/skills/$skillId',
  path: '/skills/$skillId',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsNewRoute = SkillsNewRouteImport.update({
  id: '/skills/new',
  path: '/skills/new',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUsernameSkillsSkillIdRoute =
  UsersUsernameSkillsSkillIdRouteImport.update({
    id: '/users/$username/skills/$skillId',
    path: '/users/$username/skills/$skillId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/favorite': typeof FavoriteRoute
  '/hello': typeof HelloRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/skills': typeof DashboardSkillsRoute
  '/skills/$skillId': typeof SkillsSkillIdRoute
  '/skills/new': typeof SkillsNewRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/users/$username/skills/$skillId': typeof UsersUsernameSkillsSkillIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/favorite': typeof FavoriteRoute
  '/hello': typeof HelloRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/skills': typeof DashboardSkillsRoute
  '/skills/$skillId': typeof SkillsSkillIdRoute
  '/skills/new': typeof SkillsNewRoute
  '/dashboard': typeof DashboardIndexRoute
  '/users/$username/skills/$skillId': typeof UsersUsernameSkillsSkillIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/favorite': typeof FavoriteRoute
  '/hello': typeof HelloRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/skills': typeof DashboardSkillsRoute
  '/skills/$skillId': typeof SkillsSkillIdRoute
  '/skills/new': typeof SkillsNewRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/users/$username/skills/$skillId': typeof UsersUsernameSkillsSkillIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/about'
    | '/contact'
    | '/favorite'
    | '/hello'
    | '/dashboard/settings'
    | '/dashboard/skills'
    | '/skills/$skillId'
    | '/skills/new'
    | '/dashboard/'
    | '/users/$username/skills/$skillId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/favorite'
    | '/hello'
    | '/dashboard/settings'
    | '/dashboard/skills'
    | '/skills/$skillId'
    | '/skills/new'
    | '/dashboard'
    | '/users/$username/skills/$skillId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/about'
    | '/contact'
    | '/favorite'
    | '/hello'
    | '/dashboard/settings'
    | '/dashboard/skills'
    | '/skills/$skillId'
    | '/skills/new'
    | '/dashboard/'
    | '/users/$username/skills/$skillId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FavoriteRoute: typeof FavoriteRoute
  HelloRoute: typeof HelloRoute
  SkillsSkillIdRoute: typeof SkillsSkillIdRoute
  SkillsNewRoute: typeof SkillsNewRoute
  UsersUsernameSkillsSkillIdRoute: typeof UsersUsernameSkillsSkillIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorite': {
      id: '/favorite'
      path: '/favorite'
      fullPath: '/favorite'
      preLoaderRoute: typeof FavoriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hello': {
      id: '/hello'
      path: '/hello'
      fullPath: '/hello'
      preLoaderRoute: typeof HelloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/skills': {
      id: '/dashboard/skills'
      path: '/skills'
      fullPath: '/dashboard/skills'
      preLoaderRoute: typeof DashboardSkillsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/skills/$skillId': {
      id: '/skills/$skillId'
      path: '/skills/$skillId'
      fullPath: '/skills/$skillId'
      preLoaderRoute: typeof SkillsSkillIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/new': {
      id: '/skills/new'
      path: '/skills/new'
      fullPath: '/skills/new'
      preLoaderRoute: typeof SkillsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$username/skills/$skillId': {
      id: '/users/$username/skills/$skillId'
      path: '/users/$username/skills/$skillId'
      fullPath: '/users/$username/skills/$skillId'
      preLoaderRoute: typeof UsersUsernameSkillsSkillIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSkillsRoute: typeof DashboardSkillsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSkillsRoute: DashboardSkillsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FavoriteRoute: FavoriteRoute,
  HelloRoute: HelloRoute,
  SkillsSkillIdRoute: SkillsSkillIdRoute,
  SkillsNewRoute: SkillsNewRoute,
  UsersUsernameSkillsSkillIdRoute: UsersUsernameSkillsSkillIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
